name: build push image
on:
  push:
    paths-ignore:
      - ".github/**"
      - "README.md"
    branches:
      - "dev"

jobs:
  build-push-dev:
    runs-on: ubuntu-latest
    outputs:
      shashort: ${{ steps.ssha.outputs.sha_short }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set short sha
        id: ssha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: surote/py-http-echo:${{ github.sha }}

      - name: Login to QUAY
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_SECRET }}
      - name: Build and push to QUAY
        uses: docker/build-push-action@v4
        id: quay-build-push
        with:
          push: true
          tags: quay.io/${{secrets.QUAY_USER}}/py-http-header-https:${{ github.sha }}

      # Install Cosign
      - uses: sigstore/cosign-installer@main

      - name: Sign image with a key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY quay.io/${{secrets.QUAY_USER}}/py-http-header-https:${{ github.sha }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Verify image with a key
        run: |
          cosign verify --key env://COSIGN_PUBLIC_KEY quay.io/${{secrets.QUAY_USER}}/py-http-header-https:${{ github.sha }}
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
