name: build push image
on:
  push:
    paths-ignore:
      - ".github/**"
      - "README.md"
    branches:
      - "dev"

jobs:
  build-push-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: surote/py-http-echo:${{ github.sha }}

      - name: Login to QUAY
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_SECRET }}
      - name: Build and push to QUAY
        uses: docker/build-push-action@v4
        id: quay-build-push
        with:
          push: true
          tags: quay.io/${{secrets.QUAY_USER}}/py-http-header:${{ github.sha }}

      # Install Cosign
      - uses: sigstore/cosign-installer@main

      - name: Sign image with a key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY quay.io/${{secrets.QUAY_USER}}/py-http-header:${{ github.sha }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Verify image with a key
        run: |
          cosign verify --key env://COSIGN_PUBLIC_KEY quay.io/${{secrets.QUAY_USER}}/py-http-header:${{ github.sha }}
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}

  checkout-deployment:
    runs-on: ubuntu-latest
    needs: build-push-dev
    steps:
      - name: Checkout deployment
        uses: actions/checkout@v4
        with:
          repository: Surote/demo-kustomize
          token: ${{ secrets.GH_PAT }}

      - name: Set new image
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers[0].image="quay.io/rh_ee_swongpai/py-http-header:${{ github.sha }}"' env/dev/deployment.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update DEV image ${{ github.sha }}
          title: Update DEV image
          body: Update DEV image
          branch: dev-update-image